### ISSUE TITLE
Does this asset work with current versions of Unity ie 2020 and 2021?

### ISSUE THREAD

**Issue by ToxMox** [Radivarig/GUI-Node-Editor_docs-and-issue-tracker#1]
Hi,

I'm considering purchasing this asset but I would like to verify it works with current Unity versions first?

Thanks!

**Comment by Radivarig** [comment]
Yes, I last tested with 2020.3.5f1

**Comment by ToxMox** [comment]
Ah great! I will probably purchase today or tomorrow :)
Thank you for the quick response 👍

**Comment by Radivarig** [comment]
No problem :)
