### ISSUE TITLE
Can't get demo scene to work properly when importing into my project.

### ISSUE THREAD

**Issue by ToxMox** [Radivarig/GUI-Node-Editor_docs-and-issue-tracker#2]
Hi. Please see https://youtu.be/CWxU3_2W-2Q for an example of me trying to use the demo scene when I import the asset into my 2020.3.5f1 URP project. If I import into a new blank 2020.3.5f1 URP project the Demo scene works as intended.

You can see in the video that the nodes don't really do anything. The WASD keys don't trigger anything etc.

I'm also including a screenshot of the In Project Packages if that helps.
![Unity_20210429_145532](https://user-images.githubusercontent.com/22566356/116603495-f9baee80-a8fa-11eb-8d0d-7af44c61a3bf.png)

Any insight on what may cause this? I get no errors or anything.

Thanks!

**Comment by Radivarig** [comment]
Hm, that is weird. From the video I see that the time output is not changing, keeps displaying `53.97`.
Are you doing something like `Time.timeScale = 0;` from a script?

**Comment by ToxMox** [comment]
I didn't modify the demo scene at all and I don't think I've done anything at all to timescale in the project.

**Comment by Radivarig** [comment]
Just to rule this out, can you check the values under `Edit > Project Settings > Time`?

And for play mode, attach this script on any GameObject and see the outputs.
Also tick `Console > Collapse` to reduce output to just what changes.
```cs
using UnityEngine;

public class LogStuff : MonoBehaviour
{
    void Update()
    {
        Debug.Log("Time.time: " + Time.time);
        Debug.Log("Time.timeScale: " + Time.timeScale);
    }
}
```

**Comment by ToxMox** [comment]
Here are my time settings as well as the log which was updating the time correctly every second in the log. I tried changing my Fixed Timestep to .02 just in case since that's default but made no difference.
![Unity_20210429_161539](https://user-images.githubusercontent.com/22566356/116613193-625b9880-a906-11eb-93d9-3b61d9f0d6c3.png)
![Unity_20210429_161639](https://user-images.githubusercontent.com/22566356/116613194-625b9880-a906-11eb-927f-6fb171189c14.png)

**Comment by Radivarig** [comment]
Can you try cloning the project directory, remove files related to your project to make a minimal example, test to confirm it still is not working and send me the zipped project on my email?

**Comment by ToxMox** [comment]
So while I was working on doing what you asked I was digging around during playback and I think I discovered something that might help. 

In the demo scene for the 3 SwitchNodeEditors (ColorBlendEditor, EnumStateEditor, and MovementEditor), they all had the Node Editor (Script) disabled. If I enable the checkbox for those 3 then it all seems to work fine. Not sure if this even warrants a fix or anything as it seems like all is good if I just make sure to enable the NodeEditor.cs script. 

I'm sure you understand better what's happening than I do lol :)

**Comment by Radivarig** [comment]
Ah, ok.

So there are two components relevant for this, one is `NodeEditor` which is what runs the logic, if this is turned off then its part won't work. If you import the fresh demo you'll see those are enabled.

The second is `RuntimeNodeEditor` which is the visual part, this is turned off when not needed, and when you click the buttons in the demo top right corner, you can see them being toggled to show different nodes on screen.

It seems that you tried to disable GUI (runtime) but disabled the logic instead, which would load the state of the nodes from the save file called `ColorBlendEditorSaves/demo.txt` that has a serialized value `"name":"time","value":{"$content":53.96946...` and corresponds to the magic `53.97` seconds from the video.

**Comment by ToxMox** [comment]
It's really strange. I didn't manually disable them or anything I simply imported the package and then opened the demo scene and ran it. I hadn't even expanded the SwitchNodeEditors object. When importing into a new blank project the script stays enabled. I'm not sure what made that script on all 3 objects turn off on import into my main project but I'm not going to worry about it and just wanted you to know it wasn't me that turned them off :)

Thank you for your help and quick responses! 👍

**Comment by Radivarig** [comment]
Then I'm baffled as well x) No problem!
