### ISSUE TITLE
Time node doesn't work

### ISSUE THREAD

**Issue by ArEnSc** [Radivarig/GUI-Node-Editor_docs-and-issue-tracker#4]
Hey I am using the latest unity right now and the time node doesn't work. I am not sure why I double checked the node. and even put a print statement there it does nothing. In the demo it also does nothing thanks!

**Comment by Radivarig** [comment]
Hi, can you please post the full version name?

**Comment by ArEnSc** [comment]
> Hi, can you please post the full version name?

Hey I played around with it and it worked out I think there is just a bug starting the initial graph, you have check mark it in the player in the demo.

It there a way to change the header color, font, and dock colors of each node? Thanks

**Comment by Radivarig** [comment]
Sorry I've only seen your first sentence in the email.

Yes you can change colors, please look into the `GUISkin guiSkin` field on the NodeEditorConfig.

**Comment by Radivarig** [comment]
What do you mean check mark it in the player? Can you post a screenshot please?

**Comment by ArEnSc** [comment]
Oh what I mean is when you run the sample the first time the demo doesn't start, so I have to enable the game object in the scene hierarchy to get it to run
